spring.application.name=Application
spring.datasource.url=jdbc:postgresql://localhost:5432/BusBooking
spring.datasource.username=postgres
spring.datasource.password=Riya1109*
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa..hibernate.ddl-auto=update
